name: flutterui
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/profiles/
    - assets/shared/

  # example:
  fonts:
     - family: "SFDisplay"
       fonts:
         - asset: assets/fonts/SFDisplay-Bold.otf
         - asset: assets/fonts/SFDisplay-Light.otf
         - asset: assets/fonts/SFDisplay-Medium.otf
         - asset: assets/fonts/SFDisplay-Regular.otf
         - asset: assets/fonts/SFDisplay-Semibold.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
